backend/core/urls.py
from django.urls import path
from backend.core import views as v

app_name = 'core'

urlpatterns = [
    path('', v.index, name='index'),
]

backend/servico/urls.py
from django.urls import path
from backend.servico import views as v

app_name = 'servico'

urlpatterns = [
    path('', v.ordem_servico_list, name='ordem_servico_list'),
    path('create/', v.ordem_servico_create, name='ordem_servico_create'),
    path('<int:pk>/', v.ordem_servico_detail, name='ordem_servico_detail'),
    path('<int:pk>/update', v.ordem_servico_update, name='ordem_servico_update'),
    path('<int:pk>/delete', v.ordem_servico_delete, name='ordem_servico_delete'),
]

backend/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('',include('backend.core.urls', namespace='core')),
    path('servico/',include('backend.servico.urls', namespace='servico')),
    path('admin/', admin.site.urls),
]

backend/core/models.py
from django.db import models
from localflavor.br.br_states import STATE_CHOICES


class Endereco(models.Model):
    endereco = models.CharField(
        'endereço',
        max_length=100,
        null=True,
        blank=True
    )
    complemento = models.CharField(
        'complemento',
        max_length=100,
        null=True,
        blank=True
    )
    bairro = models.CharField(
        'bairro',
        max_length=100,
        null=True,
        blank=True
    )
    cidade = models.CharField('cidade', max_length=100, null=True, blank=True)
    uf = models.CharField(
        'UF',
        max_length=2,
        choices=STATE_CHOICES,
        null=True,
        blank=True
    )
    cep = models.CharField('CEP', max_length=9, null=True, blank=True)

    class Meta:
        abstract = True

backend/crm/models.py
from django.db import models
from django.urls import reverse_lazy

from backend.core.models import Endereco


class Cliente(Endereco):
    razao_social = models.CharField('Razão Social', max_length=120, unique=True)
    cnpj = models.CharField('CNPJ', max_length=14, null=True, blank=True)

    class Meta:
        ordering = ('razao_social',)
        verbose_name = 'cliente'
        verbose_name_plural = 'clientes'

    def __str__(self):
        return f'{self.razao_social}'

    def get_absolute_url(self):
        return reverse_lazy('crm:cliente_detail', kwargs={'pk': self.pk})

backend/servico/models.py
from django.db import models

from backend.crm.models import Cliente


class Servico(models.Model):
    titulo = models.CharField('Título', max_length=100)

    class Meta:
        ordering = ('titulo',)
        verbose_name = 'serviço'
        verbose_name_plural = 'serviços'

    def __str__(self):
        return f'{self.titulo}'

# Enum Status do Servico
SITUACAO = (
    ('pe', 'Pendente'),
    ('ca', 'Cancelado'),
    ('an', 'Andamento'),
    ('ap', 'Aprovado'),
)


class OrdemServico(models.Model):
    situacao = models.CharField('Situação', max_length=2, choices=SITUACAO)
    cliente = models.ForeignKey(
        Cliente,
        on_delete=models.SET_NULL,
        verbose_name='cliente',
        related_name='ordem_servicos',
        null=True,
        blank=True
    )

    class Meta:
        ordering = ('-pk',)
        verbose_name = 'ordem de serviço'
        verbose_name_plural = 'ordens de serviço'

    def __str__(self):
        return f'{self.pk}'


class OrdemServicoItem(models.Model):
    ordem_servico = models.ForeignKey(
        OrdemServico,
        on_delete=models.CASCADE,
        verbose_name='ordem de serviço',
        related_name='ordem_servico_itens',
    )
    servico = models.ForeignKey(
        Servico,
        on_delete=models.CASCADE,
        verbose_name='serviço',
        related_name='ordem_servico_item_servicos',
    )
    valor = models.DecimalField('valor', max_digits=8, decimal_places=2, null=True, blank=True)
    proxima_visita = models.DateField('Próxima Visita', null=True, blank=True)

    class Meta:
        ordering = ('-pk',)  # ordem decrescente, se quiser crescente só tirar o sinal de menos.
        verbose_name = 'item da ordem de serviço'
        verbose_name_plural = 'itens da ordens de serviço'

    def __str__(self):
        return f'{self.pk}'

backend/servico/forms.py
from django import forms

from .models import OrdemServico


class OrdemServicoForm(forms.ModelForm):
    servico = forms.CharField()
    valor = forms.DecimalField()
    proxima_visita = forms.DateField(
        label='Próxima Visita',
        required=False,
        widget=forms.DateInput(
            format='%Y-%m-%d',
            attrs={
                'type': 'date',
                'class': 'form-control'
            }),
        input_formats=('%Y-%m-%d',),
    )

    class Meta:
        model = OrdemServico
        fields = ('situacao',)

backend/core/views.py
from django.shortcuts import render

def index(request):
    template_name = 'index.html'
    return render(request, template_name)

backend/crm/views.py
from django.shortcuts import render

# Create your views here.

backend/servico/views.py
from django.shortcuts import render
from .models import OrdemServico

def ordem_servico_list(request):
    template_name = 'servico/ordem_servico_list.html'
    object_list = OrdemServico.objects.all()
    context = {
        'object_list': object_list
    }
    return render(request, template_name, context)

    
def ordem_servico_create(request):
    template_name = 'servico/ordem_servico_form.html'
    return render(request, template_name)

def ordem_servico_detail(request,pk):
    template_name = 'servico/ordem_servico_detail.html'
    instance = OrdemServico.objects.get(pk=pk)
    context = {'object': instance}
    return render(request, template_name, context)

def ordem_servico_update(request,pk):
    ...
def ordem_servico_delete(request,pk):
    ...

backend/core/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ordem de Serviço</title>

    <!-- Bootstrap 5.2 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" rel="stylesheet">

    <!-- Alpine.js -->
    <script src="https://cdn.jsdelivr.net/npm/alpinejs@3.10.3/dist/cdn.min.js" defer></script>

    <!-- HTMX -->
    <script src="https://unpkg.com/htmx.org@1.9.3"></script>

    <style>
    body{
        background-color: #d6d6d6;
    }
        /* Custom CSS to remove border from navbar-toggler */
        .navbar-toggler {
            border: none;
            box-shadow: none; /* Remove shadow if any */
        }
        /* Remove outline on focus */
        .navbar-toggler:focus, .navbar-toggler:active {
            outline: none; /* Remove the outline when focused or active */
            box-shadow: none; /* Remove any box-shadow on focus or active state */
        }

        /* Optional: Remove border when clicked */
        .navbar-toggler:focus, .navbar-toggler:active {
            border: none;
        }
        .dropdown-menu {
            width: 300px; /* Ajuste a largura conforme necessário */
            padding: 0;
            overflow: hidden; /* Garante que o conteúdo não saia do dropdown */
        }
        .navbar-login {
            padding: 1rem;
        }
        .navbar-login .icon-size {
            font-size: 3rem; /* Ajuste o tamanho do ícone conforme necessário */
        }
        .navbar-login-session {
            border-top: 1px solid #ddd;
        }
        .btn-block {
            display: block;
            width: 100%;
        }
        .dropdown-menu .row {
            margin-left: 0;
            margin-right: 0;
        }
        .dropdown-menu .col-lg-4,
        .dropdown-menu .col-lg-8 {
            padding-left: 0;
            padding-right: 0;
        }
        .dropdown-menu .text-left {
            text-align: left;
        }
        .dropdown-menu .dropdown-item {
            white-space: nowrap; /* Evita quebra de linha dentro dos itens do dropdown */
        }
        .dropdown-menu .btn-block {
            width: auto; /* Ajusta a largura dos botões dentro do dropdown */
        }        
        a {
            text-decoration: none;
        }
        .btn-icon {
            width: 40px; /* Define a largura do botão */
            height: 40px; /* Define a altura do botão */
            padding: 0; /* Remove o preenchimento interno */
            border-radius: 50%; /* Torna o botão circular */
            display: flex;
            align-items: center;
            justify-content: center;
        }      
        {% comment %} .table{
            background-color:#ffffff;
        } {% endcomment %}
    </style>
    </style>
</head>

<body>
    <nav class="navbar navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
            <!-- Botão Navbar Toggler -->
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                <i class="fas fa-bars"></i>
            </button>

            <!-- Dropdown do Usuário -->
            <div class="dropdown ms-auto">
                <button class="btn btn-dark dropdown-toggle" type="button" id="userDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fas fa-user"></i>
                </button>
                <ul class="dropdown-menu dropdown-menu-light dropdown-menu-end" aria-labelledby="userDropdown">
                    <li>
                        <div class="navbar-login">
                            <div class="row no-gutters">
                                <div class="col-lg-4 text-center">
                                    <p>
                                        <i class="fas fa-user icon-size"></i>
                                    </p>
                                </div>
                                <div class="col-lg-8">
                                    <p class="text-left"><strong>Ricardo Paulino do Nascimento</strong></p>
                                    <p class="text-left">
                                        <a href="#" class="btn btn-primary btn-block btn-sm">Atualizar Dados</a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </li>
                  
                    <li>
                        <div class="navbar-login navbar-login-session">
                            <div class="row no-gutters">
                                <div class="col-lg-12">
                                    <p>
                                        <a href="#" class="btn btn-danger btn-block">Sair</a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>

            <!-- Offcanvas Menu -->
            <div class="offcanvas offcanvas-start text-bg-dark" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Ordem Serviço</h5>
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <ul class="navbar-nav justify-content-start flex-grow-1 pe-3">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'core:index' %}">Home</a>
                        </li> 
                        <hr/>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'servico:ordem_servico_list' %}">Ordens de Serviço</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>

    <!-- Placeholder content block for template -->
    <div class="container-fluid" style="margin-top: 60px;">
        {% block content %}       
        {% endblock content %}
    </div>

</body>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>

</html>

backend/core/templates/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Index</h1>
<p>Content goes here.</p>
{% endblock content %}

backend/servico/templates/servico/ordem_servico_detail.html
<!-- ordem_servico_detail.html -->
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'core:index' %}">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'servico:ordem_servico_list' %}">Ordens Serviço</a></li>
        <li class="breadcrumb-item active" aria-current="page">OS {{ object }} - {{ object.cliente }}</li>
    </ol>
    </nav>

 <h3>{{ object.cliente }}</h3>

  <table class="table table-striped shadow table-hover mt-5 bg-white">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Serviço</th>
        <th scope="col">Valor</th>
        <th scope="col">Próxima Visita</th>
      </tr>
    </thead>
    <tbody>
      {% for item in object.ordem_servico_itens.all %}
        <tr>
          <td>{{ item.servico }}</td>
          <td>{{ item.valor }}</td>
          <td>{{ item.proxima_visita|date:"d/m/Y" }}</td>
        </tr>
      {% endfor %}
    </tbody>
</table>

</div>
{% endblock content %}

backend/servico/templates/servico/ordem_servico_form.html
<!-- ordem_servico_form.html -->
{% extends "base.html" %}
{% load static %}
{% load widget_tweaks %}

{% block css %}
  <link
    rel="stylesheet"
    href="{% static 'css/autocomplete.css' %}"
  >
{% endblock css %}
{% block content %}
<div class="container">
    <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'core:index' %}">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'servico:ordem_servico_list' %}">Ordens Serviço</a></li>
        <li class="breadcrumb-item active" aria-current="page">Adicionar Ordem de Serviço</li>
    </ol>
    </nav>

     <div x-data="getData">
    <h3>adicionar Ordem de Serviço</h3>
    <hr/>

    <form>
{% comment %} 
    <!-- busca cliente -->
      <div class="form-group row autocomplete">
        <label
          for=""
          class="col-sm-2 col-form-label"
        >Cliente</label>
        <div class="col-sm-10">
        <!-- manual -->
          <input
            type="text"
            class="form-control"
            placeholder="Cliente"
            x-model="searchCliente"
          >
          <ul
            id="id_ul"
            x-show="clienteShow"
          >
            <template
              x-for="cliente in clientes"
              :key="cliente.id"
            >
              <li
                x-text="cliente.razao_social"
                @click="getCliente(cliente)"
              ></li>
            </template>
          </ul>
        </div>
      </div>

      <div class="form-group row">
        <label
          for=""
          class="col-sm-2 col-form-label"
        >Situação</label>
        <div class="col-sm-10">
        <!-- widget_tweaks -->
          {% render_field form.situacao class="form-control" x-model="ordemServico.situacao" %}
        </div>
      </div>

      <p>Endereço: <span x-text="clienteSelecionado.endereco"></span></p>
      <p>Bairro: <span x-text="clienteSelecionado.bairro"></span></p>

    <!-- busca servico -->
      <div class="form-group row autocomplete">
        <label
          for=""
          class="col-sm-2 col-form-label"
        >Serviço</label>
        <div class="col-sm-10">
        <!-- manual -->
          <input
            type="text"
            class="form-control"
            placeholder="servico"
            x-model="searchServico"
          >
          <ul
            id="id_ul"
            x-show="servicoShow"
          >
            <template
              x-for="servico in servicos"
              :key="servico.id"
            >
              <li
                x-text="servico.titulo"
                @click="getServico(servico)"
              ></li>
            </template>
          </ul>
        </div>
        <p x-text="searchServico"></p>
      </div>

    <!-- <p x-text="servicoSelecionado.id"></p> -->

      <div class="form-group row">
        <label
          for=""
          class="col-sm-2 col-form-label"
        >Valor</label>
        <div class="col-sm-10">
          {% render_field form.valor class="form-control" min="0" step="0.01" x-model="ordemServicoItem.valor" %}
        </div>
      </div>

      <div class="form-group row">
        <label
          for=""
          class="col-sm-2 col-form-label"
        >Próxima Visita</label>
        <div class="col-sm-10">
          {% render_field form.proxima_visita class="form-control" x-model="ordemServicoItem.proximaVisita" %}
        </div>
      </div>

      <div class="form-group row">
        <div class="col-sm-10">
          <button
            type="button"
            class="btn btn-primary"
            @click="addItem"
          >Adicionar</button>
          <button
            type="submit"
            class="btn btn-success"
          >Salvar</button>
        </div>
      </div> {% endcomment %}

    </form>

    <table class="table table-striped shadow table-hover mt-3 bg-white">
        <thead class="thead-dark">
        <tr>
          <th>Descrição (Serviço)</th>
          <th>Valor</th>
          <th>Próx. Visita</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        <template
          x-for="item in ordemServicoItems"
          :key="item.id"
        >
          <tr>
            <td x-text="item.servico_titulo"></td>
            <td x-text="item.valor"></td>
            <td x-text="item.proxima_visita"></td>
            <td
              class="text-primary"
              @click="deleteOrdemServicoItem(item.id)"
            >Deletar</td>
          </tr>
        </template>
      </tbody>
    </table>
  </div>
</div>

{% endblock content %}

{% block js %}
  <script
    src="{% static 'js/servico/servico.js' %}"
    data-csrf="{{ csrf_token }}"
  ></script>
{% endblock js %}

backend/servico/templates/servico/ordem_servico_list.html
<!-- ordem_servico_list.html -->
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'core:index' %}">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Ordens</li>
    </ol>
    </nav>

    <h3>ordens de serviço</h3>
    <hr/>
    <!-- Adicionar botão -->
        <a href="{% url 'servico:ordem_servico_create' %}" class="btn btn-primary btn-icon mb-3">
            <i class="fas fa-plus"></i>
        </a>   
    
    <table class="table table-striped shadow table-hover mt-3 bg-white">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Nº</th>
                <th scope="col">Cliente</th>
                <th scope="col">Situação</th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
            <tr>
                <td>{{ object.pk }}</td>
                <td><a href="{% url 'servico:ordem_servico_detail' object.pk %}">{{ object.cliente }}</a></td>
                <td>{{ object.get_situacao_display }}</td>
            </tr>
            {% endfor %}        
        </tbody>
    </table>
</div>
{% endblock content %}